import api from '@/product/api';
import Head from 'next/head';
import { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import DataTable from './DataTable';

function Home({ products }: InferGetServerSidePropsType<typeof getServerSideProps>) {
    return (
        <>
            <Head>
                <title>Gestión con Google Sheets</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main>
                <h1>Gestión con Google Sheets</h1>
                <DataTable products={products} />
            </main>
        </>
    );
}

export const getServerSideProps: GetServerSideProps = async () => {
    const products = await api.list();
    return {
        props: {
            products,
        },
    };
};

export default Home;
