import Head from 'next/head';
import DataTable from './DataTable';
import { Box, Text } from '@chakra-ui/react';
import { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import api from '@/product/api';

function Home({ products }: InferGetServerSidePropsType<typeof getServerSideProps>) {
    return (
        <>
            <Head>
                <title>Gestión con Google Sheets</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main>
                <Box textAlign='center' my={4}>
                    <Text color='text' fontWeight='semibold' fontSize={24}>
                        Gestión con Google Sheets
                    </Text>
                </Box>
                <DataTable products={products} />
            </main>
        </>
    );
}

export const getServerSideProps: GetServerSideProps = async () => {
    const products = await api.list();
    return {
        props: {
            products,
        },
    };
};

export default Home;
